name: wgbs-core
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - annotated-types=0.7.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=25.3.0
  - bismark=0.24.2
  - bowtie2=2.5.4
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - comm=0.2.2
  - coreutils=9.5
  - cpython=3.13.5
  - curl=8.14.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.15.0
  - freetype=2.13.3
  - h2=4.2.0
  - hisat2=2.2.1
  - hpack=4.1.0
  - htslib=1.22.1
  - humanfriendly=10.0
  - humanize=4.12.3
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - k8=1.2
  - kaleido-core=0.2.1
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.14.4
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - markdown=3.8.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mathjax=2.7.7
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minimap2=2.30
  - multiqc=1.30
  - narwhals=1.47.0
  - natsort=8.4.0
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nextflow=25.04.6
  - numpy=2.3.1
  - openjdk=23.0.2
  - openjpeg=2.5.3
  - openssl=3.5.1
  - packaging=25.0
  - parso=0.8.4
  - perl=5.32.1
  - perl-alien-build=2.84
  - perl-alien-build-plugin-download-gitlab=0.01
  - perl-alien-libxml2=0.20
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-capture-tiny=0.48
  - perl-carp=1.38
  - perl-constant=1.33
  - perl-data-dumper=2.183
  - perl-encode=3.21
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.70
  - perl-ffi-checklib=0.28
  - perl-file-chdir=0.1010
  - perl-file-path=2.18
  - perl-file-temp=0.2304
  - perl-file-which=1.24
  - perl-importer=0.026
  - perl-mime-base64=3.16
  - perl-parent=0.236
  - perl-path-tiny=0.122
  - perl-pathtools=3.75
  - perl-scope-guard=0.21
  - perl-storable=3.15
  - perl-sub-info=0.002
  - perl-term-table=0.024
  - perl-test2-suite=0.000163
  - perl-uri=5.12
  - perl-xml-libxml=2.0210
  - perl-xml-namespacesupport=1.12
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - plotly=6.2.0
  - polars=1.31.0
  - polars-default=1.31.0
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyaml-env=1.2.2
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-gil=3.13.5
  - python-kaleido=0.2.1
  - python_abi=3.13
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.4
  - rich=14.0.0
  - rich-click=1.8.9
  - rpds-py=0.26.0
  - samtools=1.22.1
  - six=1.17.0
  - spectra=0.0.11
  - sra-tools=3.2.1
  - stack_data=0.6.3
  - tiktoken=0.9.0
  - tk=8.6.13
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typeguard=4.4.4
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.2
      - cutadapt==5.1
      - cycler==0.12.1
      - dnaio==1.2.3
      - fonttools==4.58.5
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - pandas==2.3.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - tzdata==2025.2
      - xopen==2.0.2

